### ISSUE TITLE
Backup aircraft firmware file always invalid...

### ISSUE THREAD

**Issue by localhorst24** [jezzab/DUMLdore#11]
...when i try to load the saved backup firmware file.
(mavic pro firmware .1000)

**Comment by jezzab** [comment]
You need to provide a bit more information:
What version of DUMLdore are you running?
What is the file size of the backup?

**Comment by localhorst24** [comment]
DUMLdore V1.90 (V1.90.0.0)
The file size is 110.141.440 Bytes for the [Aircraft](https://www.dropbox.com/s/p3m3csv05e64xkb/Aircraft%20dji_system.bin?dl=1) and 217.190.400 Bytes for the [Remote Control](https://www.dropbox.com/s/haadhfkwti3xftx/Remote%20Controler%20dji_system.bin?dl=1).
No Problems at all (Win10x64).

**Comment by jezzab** [comment]
For some reason the files have not been decrypted correctly. 
Also it looks like the first backup file was not moved before the second backup was done.
Did you download the entire zip file?

**Comment by jezzab** [comment]
Please download and test the latest version (you will need to make a new backup with it). Tested and working here. They changed the encryption keys :)

**Comment by localhorst24** [comment]
Thank you :)
