### ISSUE TITLE
First flash no go

### ISSUE THREAD

**Issue by jcarlo70** [jezzab/DUMLdore#13]
I'm using the latest DUMLdore version but even the previous ones.  I have to flash twice before it initiates upgrade. I'm using Mavic Pro.  Downgrading or upgrading 400/700.  Only does it on Mavic and not RC.  But it does upgrade completely to 100%

Jcarlo

[upgrade00_logjam.txt](https://github.com/jezzab/DUMLdore/files/1286846/upgrade00_logjam.txt)

**Comment by jezzab** [comment]
Unfortunately I am unable to replicate it here and don't have a solution for you at the moment sorry.
