### ISSUE TITLE
support for FW04.0100

### ISSUE THREAD

**Issue by ROGMAO** [jezzab/DUMLdore#19]
FW04.0100 cannot connect, COM connected was shown but failed to connect to FTP and RNDIS

**Comment by jezzab** [comment]
FW 1.4.0100 is not supported at this time due to changes in the file system. You will be unable to backup or downgrade.

**Comment by djisb** [comment]
When is the support of FW04.0100？

**Comment by jezzab** [comment]
When it is

**Comment by djisb** [comment]
Because FW1.04.0100 is too bad, I want to roll back, so I ask you to update it as soon as possible.

**Comment by jezzab** [comment]
If only it was that simple....
