### ISSUE TITLE
 FW1.04.0100

### ISSUE THREAD

**Issue by djisb** [jezzab/DUMLdore#20]
sorry，My English is very poor， I use the translation software，Not intentionally offending you，i wait u，I believe u can.

**Comment by djisb** [comment]
Please forgive me. I didn't mean to offend you by saying that

**Comment by zqg1020** [comment]
你显示主控数据异常问题解决了吗？我也碰到这样问题，可以加微信pcp20160520交流一下吗？

**Comment by jezzab** [comment]
https://github.com/jezzab/DUMLdore/releases/tag/v3.00
