### ISSUE TITLE
Drone locking

### ISSUE THREAD

**Issue by TheGranolaBoy** [jezzab/DUMLdore#35]
Ok, is there any way to keep the drone for locking everytime I turn it on? I'm running the firmware that allows height limits to be tweaked so I have to run this tool every time.

**Comment by jezzab** [comment]
What aircraft? Is it a Spark?

**Comment by TheGranolaBoy** [comment]
Yes, Yes it is.

**Comment by jezzab** [comment]
Early Spark fw version was enforced to lock by DJI on a certain date by the APP due to a required battery update. You need to unlock and then stay offline (or run an offline modded app) or the app will lock the AC again.
https://github.com/Bin4ry/deejayeye-modder

**Comment by danieltroger** [comment]
You can now patch newer firmware versions too with this tool: https://github.com/o-gs/DJI_FC_Patcher
