### ISSUE TITLE
connecting DJI issue 

### ISSUE THREAD

**Issue by virusozee** [jezzab/DUMLdore#36]
when  i open dumbldore  it says  "\ serial port not found,    please help

**Comment by Mavic129** [comment]
There are 2 serial ports, you need to disable the VPS serial port

**Comment by Mavic129** [comment]
If you are on slack, please DM on my ID: the_LORD

**Comment by virusozee** [comment]
Hi

I opened a slack account  but have no idea how to add you    the_lord

Could you possibly help me via email or Skype? Etc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
