### ISSUE TITLE
Mavic 2 Pro

### ISSUE THREAD

**Issue by tathanhdat1990** [jezzab/DUMLdore#41]
Dear Admin
I have a mavic 2 pro brandnew in seal, i buy in ebay. But can't active my Mavic pro 2, error code 400. I pm support DJI, he say my item is one of the units stolen in transit, It is recommended to contact the seller and ask for the refund ( impossible ). I can't pm seller, he don't reply. 
I search in DJI forum, somebody similar me
https://forum.dji.com/thread-162236-1-1.html
Please help me active my Drone.
Thanks so much﻿. 
P/S : I try to use your tool but Button Active no available. So sad :(

**Comment by jezzab** [comment]
Submit in a PayPal dispute. I cant help you sorry.

**Comment by tathanhdat1990** [comment]
Thanks Admin.
