### ISSUE TITLE
anti-rollback file is missing or corrupt from dumldore

### ISSUE THREAD

**Issue by jiekchenid** [jezzab/DUMLdore#46]
anti-rollback file is missing or corrupt from dumldore re-down zip file from.......and re-install  when use V3.10   V3.0 flash fw  dont work in win10  transferring to device the program is shutdown
![image](https://user-images.githubusercontent.com/460270/52163591-fd149f00-271e-11e9-8f8a-ec3f04820c77.png)

**Comment by jiekchenid** [comment]
CLR20r3

**Comment by rectalsweeper** [comment]
you have to downloade the zip not only the .exe
