### ISSUE TITLE
dumldore

### ISSUE THREAD

**Issue by lagerlawson** [jezzab/DUMLdore#47]
I need to roll back my drone hardware and I have mac OS.  Is there a compatible version of Dumldore?

**Comment by cn1995640** [comment]
You can find the source code from https://github.com/jezzab/DUMLdore/releases

**Comment by cn1995640** [comment]
You can find the source code from https://github.com/jezzab/DUMLdore/releases

**Comment by cn1995640** [comment]
> I need to roll back my drone hardware and I have mac OS. Is there a compatible version of Dumldore?

You can find the source code from https://github.com/jezzab/DUMLdore/releases

**Comment by vladsol** [comment]
> source code

But... There is binaries only :)

**Comment by jezzab** [comment]
There is no macOS version and wont be in the future sorry. You will have to either borrow a friends PC, Boot Camp your Mac or run a VM
