### ISSUE TITLE
cannot rollback my mavic pro one from 01.04.500 to 01.03.900

### ISSUE THREAD

**Issue by zhaodelong** [jezzab/DUMLdore#48]
I tried to roll back my mavic pro from 01.04.500 to 01.03.900. The tool reported roll back completed. But after restart, the version is still 01.04.500. Any thoughts?

**Comment by kilrah** [comment]
Roll back with assistant as far back as you can, then use dumldore to go further back if needed.

**Comment by zhaodelong** [comment]
solved this issue by rollback from 01.04.500 to 01.04.400 first. And then it can be further back. Thanks.
