### ISSUE TITLE
Enhancement: Pull upgrade00.log

### ISSUE THREAD

**Issue by kilrah** [jezzab/DUMLdore#5]
Since the whole mechanism to decrypt FTP files is in place, it could be useful for troubleshooting to add a button with a one-click way for people to pull their upgrade log

**Comment by jezzab** [comment]
https://github.com/MAVProxyUser/DJI_ftpd_aes_unscramble

**Comment by kilrah** [comment]
Sure, but DUMLdore was made for people who couldn't easily fiddle with a python script and FTP client, so it only makes sense that once they've up/downgraded using DUMLdore and still have it open they can just click a button to get the log if there was an issue...

This was in response to a thread that is now posted on DUMLdore usage on a user forum where someone had an issue - they could click the DUMLdore buttons, but them not being savvy with the other tools to get the log it makes troubleshooting difficult.

**Comment by MAVProxyUser** [comment]
@kilrah  this outta do it... 
https://github.com/MAVProxyUser/DUMLrub/releases/download/v.01/LogJammer.zip
https://github.com/MAVProxyUser/DUMLrub/blob/master/LogJammer.rb
