### ISSUE TITLE
"Dumldore has stopped working" error

### ISSUE THREAD

**Issue by esuohdica** [jezzab/DUMLdore#53]
Hi Jezzab,

I'm stuck with Dumldore V3.20 unable to start on my home PC, i just get "Dumldore has stopped working" straight away. I've tried removing and reinstalling, but no success. I get the same message whether or not I have the Mavic connected.
What is Dumldore looking for as it starts? I'm sure this is either driver or port related, because everything works fine on a different laptop, it just frustrating that i can't fix this one!
I can FTP into the Mavic when its connected and assistant also connects no problem. Any ideas? Cheers
![Capture1](https://user-images.githubusercontent.com/50531321/60138169-42ef0400-97a1-11e9-9192-982be5285db9.PNG)
![Capture2](https://user-images.githubusercontent.com/50531321/60138172-45515e00-97a1-11e9-84f0-1e669d498ecb.PNG)

**Comment by jezzab** [comment]
It sounds like a comport/serial port problem and the way the very old version of Windows you are running handles it (Windows 7 is very sketchy with comport handling and VCP drivers). Have a look as some of the old issue requests for possible fixes. You probably have 2 DJI comports when you should only have one. One of them is "dead" and its trying to talk to that one.

**Comment by esuohdica** [comment]
Thanks Jezzab, i couldn't fix the issue on the original PC, but did get everything working on a second laptop (still windows7) cheers for the help, I think it is ADB driver issues, but I'm not looking any further into this as i've got a work around. Cheers
