### ISSUE TITLE
FTP error

### ISSUE THREAD

**Issue by MagicEnergy** [jezzab/DUMLdore#6]
Getting a FTP error when i try to flash the firmware.

https://image.prntscr.com/image/48BQp9nkQCCPdgb8eO2ctg.png

**Comment by MAVProxyUser** [comment]
did you test connectivity with your browser as suggested?

**Comment by MagicEnergy** [comment]
Yes no link to it. It seems not start the FTP server.

**Comment by MagicEnergy** [comment]
Yes, no link to the FTP Page. Seems that it can't setup the FTP right ( Or acces)

**Comment by MAVProxyUser** [comment]
Fix your RNDIS... this have nothing to do with DUMLdore. Reinstall Assistant software and all "drivers" and try again.
