### ISSUE TITLE
wont do offline activacion mavic 2 pro/zoom

### ISSUE THREAD

**Issue by xiraus** [jezzab/DUMLdore#62]
offline activacion wont work on mavic 2 pro/zoom on any firmware

**Comment by jezzab** [comment]
So the activate button is greyed out?

**Comment by LaughingDuck** [comment]
Yup greyed out for mavix 2 pro/zoom firmware

**Comment by LaughingDuck** [comment]
Yup greyed out for the Mavic 2 pro/zoom.

**Comment by jezzab** [comment]
Yes, that's because its not supported for activation and there is no mention of support for Mavic 2 activation. If the aircraft is supported then the button wont be greyed out.

"ACTIVATE DEVICE: Offline activate SOME devices (Mavic Pro, P4, Spark) Results may vary"
