### ISSUE TITLE
I have a mavic2 pro with firmware 01.00.510. What version do I need to roll back to, so I can install DJI assistant 1.1.2 and open parameters?

### ISSUE THREAD

**Issue by RENCG08** [jezzab/DUMLdore#65]

**Comment by xyls13** [comment]
That's impossible. I have the same machine. I've been looking for it for a long time. I don't have an old version that can downgrade the system version and adjust the parameters. Let's wait for the professionals to figure it out.

**Comment by RENCG08** [comment]
Thank you

**Comment by xyls13** [comment]
I have downloaded the historical firmware of mavic2pro, and also downloaded the 1.1.2 version of assistant 2. Do you want to try the self degraded version? If you want, I can provide you with all the tools and firmware you need. You can contact me at xueyulii@hotmail.com

**Comment by my08rubicon** [comment]
I wrote you an email. I own a DJI Mavic Pro

**Comment by xyls13** [comment]
> I wrote you an email. I own a DJI Mavic Pro

My machine model is: mavic2pro, our machine models are not the same, your mavic1pro can now use this author's software to brush the machine.

**Comment by jezzab** [comment]
Mavic 2 01.00.0510 cannot be rolled back at this time.
This issue isn't related to the functionality of DUMLdore so im closing it

**Comment by xyls13** [comment]
I've been demoted by myself. I use the latest version of assistant2 to demote successfully. Have I successfully downgraded to version 01.00.0300? Why not demote? Or the parameters cannot be modified in the degraded version?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jeremy Beall"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 下午4:12
收件人:&nbsp;"jezzab/DUMLdore"<DUMLdore@noreply.github.com&gt;;
抄送:&nbsp;"掌 心 ブ"<344269251@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jezzab/DUMLdore] I have a mavic2 pro with firmware 01.00.510. What version do I need to roll back to, so I can install DJI assistant 1.1.2 and open parameters? (#65)





 
Closed #65.

**Comment by RENCG08** [comment]
Thank you
