### ISSUE TITLE
No usb connection after flashing firmware mavic pro

### ISSUE THREAD

**Issue by dl2ffp** [jezzab/DUMLdore#69]
DUMLdore has  during flashing firmware aborted. After that, no usb connection was possible.
The usb-port try to connect and in the same time disconnect. This is ongoing.
I suspect destroyed the bootloader in the mavic pro.
Any idea ?

**Comment by jezzab** [comment]
DUMLdore does not flash the aircraft. It uploads the firmware via ftp and then tells the aircraft that it can begin an upgrade. The aircraft then upgrades itself by first checking and reading the files that were uploaded via ftp are valid, correct and not corrupt. After the moment the upgrade begins the upgrade is autonomous. The aircraft can be unplugged from USB and will continue to upgrade itself, you just wont have any feedback on the process.

Without knowing what you flashed, what firmware you were on, what you were going to, where you got it etc. I cannot help you. 

It sounds like its in a reboot loop which could be many things including a big jump in firmware version, custom scripts that were on the aircraft and so on

**Comment by dl2ffp** [comment]
After booting the aircraft is not blinking yellow, is red. I wanted firmware downgrade from 04.400 of 04.300.

**Comment by dl2ffp** [comment]
What can I do without usb? nothing or?

**Comment by dl2ffp** [comment]
I probably switched off the aircraft during the flash process

**Comment by jezzab** [comment]
Switching off the aircraft during the upgrade process could cause this and sounds more like it because going from 01.04.0400 to 01.04.0300 wont break a device. Even DJI Assistant can do this.

Im sorry but there is nothing I can suggest.
