### ISSUE TITLE
DUMLdore not opening

### ISSUE THREAD

**Issue by mrhotbox** [jezzab/DUMLdore#73]
So, when i have my dji fpv drone connected to the pc, DD will not open, it displays "querying device" before it closes again. if the done is not connected, it opens fine. have tried diffrent ports, reboot, reinstall etc. checked the other issues/tickets having similar isuues, but no go,

**Comment by jezzab** [comment]
The last DUMLdore release (https://github.com/jezzab/DUMLdore/releases/tag/v3.20) was 02 March 2019
The FPV drone was released on 02 March 2021
