### ISSUE TITLE
Timeout while trying to backup Mavic Pro v01.03.1000 firmware

### ISSUE THREAD

**Issue by musbaalbaki** [jezzab/DUMLdore#9]
This timeout is happening every single time I try to backup my current Mavic Pro firmware v01.03.1000. Note that I tried to do it many times with fully charged battery and different cables. The Mavic is connected, I can check that if I close the DUMLdore tool and open DJI Assistant 2, I can confirm the connection is working. Shall I continue to upload and flash the firmware anyway at this point? Cause I am suspecting something is wrong with my current firmware and I would like to install a fresh copy of it. I tried to install a fresh copy using DJI Assistant 2 (it went all smooth and it succeeded) but my issues with the drone persisted. Please help.
<img width="509" alt="screen shot 2017-08-28 at 9 02 01 pm" src="https://user-images.githubusercontent.com/8864462/29808702-d9ff970e-8ca1-11e7-8a5a-1e4574c146b1.png">

**Comment by jezzab** [comment]
Did you try doing what the dialog box says?

**Comment by musbaalbaki** [comment]
@jezzab Yep, I tried that but the browser hanged meaning it opened a blank page. What could cause FTP server connectivity to drop even though the Mavic is still connected. Also do you advise me to try flashing the firmware to install a fresh copy at this point? I mean even if the backend process is failing. Much appreciated

**Comment by musbaalbaki** [comment]
@jezzab I was able to reflash successfully using DJI Assistant 2 but I don't think the reflash of DJI Assistant 2  actually install a complete fresh copy so that's why I wanted to try DUMLdore but I was afraid to try flashing using DUMLdore since the backup process is timing out. Please let me know what is best to do now. Thank you in advance.

**Comment by jezzab** [comment]
You should be fine flashing. It will either upload and flash or just fail trying to upload. It wont hurt the aircraft. If the aircraft sees the file isnt there, corrupt or wrong it wont do anything.

**Comment by musbaalbaki** [comment]
Great, thank you @jezzab I will try that and see how it goes. Much appreciated!

**Comment by leonidas784** [comment]
Downgrade on Mavic Pro from v01.03.1000 work great, but backup was created uncorrectly. File dji_system.bin is 20KB long.

**Comment by jezzab** [comment]
A copy of the incorrect dji_system.bin would be good to see

**Comment by leonidas784** [comment]
1.88
Here is backup of RC 
[dji_system.zip](https://github.com/jezzab/DUMLdore/files/1260658/dji_system.zip)

**Comment by kilrah** [comment]
So you were trying to backup 1000, right? They might have changed something in that version that prevents backup from working.

**Comment by jezzab** [comment]
Tested backup of RC on .1000 - Test OK (slow but ok)

**Comment by leonidas784** [comment]
Ok, thank you. Anyway it doesn't matter. It is more iportant that flashing always working.
